### ISSUE TITLE
Meg vagyok hatva!

### ISSUE THREAD

**Issue by sedthh** [gazben/melymagyar-bingo#2]
Szia, 

én csináltam anno a Mélymagyar Bingót. Jó érzés volt látni, hogy valaki megmentette és nem veszett el. Nem gondoltam, hogy ennyire tetszik majd az embereknek. Használjátok nyugodtan, csak jelöljetek meg majd pls! 

Üdv

**Comment by gazben** [comment]
@sedthh Már kint is vagy a footerben. Köszi az alapötletet, nem telhet el nélküle a karácsony.
