### ISSUE TITLE
2020-as események

### ISSUE THREAD

**Issue by gazben** [gazben/melymagyar-bingo#23]
Ide jöhetnek az idei év eseményei.

**Comment by gazderadel** [comment]
Úgy se megyünk sehová
Aztán kitudja, hogy ebben a vakcinában is mi van...
Legyen már vége 2020-nak
Mi jöhet még?
Egymás között vagyunk, itt nem tejed a vírus
Ez a maszk is minek
1,5 méter
Kijárási tilalom
Kutyasétáltatás 
Pandémia
Karantén
Korona
Brexit
Trump
Alaptörvény
Betlehemi csillag
Hullám
Covid előtt
Mikor lesz végre normális az életünk?
Olimpia

**Comment by gazben** [comment]
Köszönjük a figyelmet idén is!
